version: '3'
services:
    php:
        build:
          context: .
          dockerfile: ./docker/local/php/Dockerfile
        working_dir: "/app"
        command: "php-fpm"
        environment:
          ALGOLIA_SECRET: "${ALGOLIA_SECRET}"
          PHP_IDE_CONFIG: "serverName=${APP_HOST}"
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./docker/local/php/config/php.ini:/usr/local/etc/php/php.ini
            - ./:/app:delegated
    nginx:
        image: nginx:latest
        depends_on:
            - php
        environment:
            APP_HOST: ${APP_HOST}
            FASTCGI_READ_TIMEOUT: 3600s
            BACKEND_ADDRESS: php
        volumes:
            - ./:/app:delegated
            - ./docker/local/nginx/templates:/etc/nginx/templates
        ports:
          - "8000:80"
    pgsql:
        image: postgres:13.3
        ports:
            - '5432:5432'
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
        volumes:
            - postgresql-data:/var/lib/postgresql/data

volumes:
    postgresql-data:
